const CANCELLATION_CODES = {
  Q1: { label: 'Missed Areas', category: 'Service / Quality' },
  Q2: { label: 'Inconsistent Tech Performance', category: 'Service / Quality' },
  Q3: { label: 'Rushed Clean / Not Detailed', category: 'Service / Quality' },
  Q4: { label: 'Repeated Same Issue', category: 'Service / Quality' },
  Q5: { label: 'Reclean Dissatisfaction', category: 'Service / Quality' },
  S1: { label: 'Tech Frequently Late', category: 'Scheduling / Consistency' },
  S2: { label: "Time Window Doesn't Work", category: 'Scheduling / Consistency' },
  S3: { label: 'Too Many Tech Changes', category: 'Scheduling / Consistency' },
  S4: { label: 'Day/Time No Longer Available', category: 'Scheduling / Consistency' },
  S5: { label: 'Last-Minute Reschedules', category: 'Scheduling / Consistency' },
  P1: { label: 'Too Expensive', category: 'Pricing / Value' },
  P2: { label: 'Comparing to Cheaper Competitor', category: 'Pricing / Value' },
  P3: { label: 'Frequency Adjustment (Downgrade)', category: 'Pricing / Value' },
  P4: { label: 'Financial Hardship', category: 'Pricing / Value' },
  P5: { label: "Didn't See Value for Price", category: 'Pricing / Value' },
  L1: { label: 'Moving', category: 'Life Changes' },
  L2: { label: 'Medical / Health', category: 'Life Changes' },
  L3: { label: 'Death in Family', category: 'Life Changes' },
  L4: { label: 'Job Loss / Income Change', category: 'Life Changes' },
  L5: { label: 'Home Sold / Renovation', category: 'Life Changes' },
  C1: { label: "Office Didn't Respond Fast Enough", category: 'Communication' },
  C2: { label: 'Misunderstood Service Level', category: 'Communication' },
  C3: { label: 'Expectation Not Set Properly', category: 'Communication' },
  C4: { label: "Tech Didn't Communicate", category: 'Communication' },
  C5: { label: 'Policy Dispute', category: 'Communication' },
  T1: { label: 'Seasonal Pause', category: 'Temporary / Pause Worthy' },
  T2: { label: 'Travel', category: 'Temporary / Pause Worthy' },
  T3: { label: 'New Baby / Temporary Overwhelm', category: 'Temporary / Pause Worthy' },
  T4: { label: 'Trialing Another Company', category: 'Temporary / Pause Worthy' },
  T5: { label: 'Wants to Resume Later', category: 'Temporary / Pause Worthy' },
  O1: { label: 'Personality Conflict', category: 'Other' },
  O2: { label: 'House Not Ready / Too Busy', category: 'Other' },
  O3: { label: 'Pet Issues', category: 'Other' },
  O4: { label: 'Unspecified', category: 'Other' },
  O5: { label: 'Other (Requires Manager Review)', category: 'Other' },
}

module.exports = CANCELLATION_CODES
